"""Tick-based dispatch loop: claim pending TicketTasks and spawn Claude sessions.

Package split (#1310, part 1). The historical flat ``cw.dispatch`` module is now
a package: ``gating`` (availability/freshness/usage-limit gates), ``claim``
(claim + spawn), ``lanes`` (lane circuit breaker / per-client dispatch), and
``_legacy`` (tick orchestration, sentinel/stage routing, event loop — the
leftover targeted by parts 2-3). This ``__init__`` re-exports the full historical
public + private surface so every ``from cw.dispatch import X`` import site and
downstream call path keeps working unchanged.
"""

from __future__ import annotations

from cw.dispatch._legacy import (
    _APPROVAL_GATE_REASON,
    _AWAITING_OPERATOR_REASON,
    _INVALID_STAGE_REASON,
    _PLAN_PARKED_REASON,
    _STAGE_REACHED_TO_STAGE,
    _UNKNOWN_CLIENT_REASON,
    _accumulate_task_cost,
    _classify_sentinel_stage_position,
    _extract_scope_tier,
    _persist_carried_context,
    _resolve_scope_tier,
    _resolve_stage_walk,
    _route_scope_gated_approval,
    _route_stage_success,
    _route_staged_decision,
    _should_gate_for_signoff,
    _stage_advance_unchecked,
    _StagePosition,
    _walk_stage_pointer_forward,
    apply_staged_decision,
    resolve_signoff,
)
from cw.dispatch.claim import (
    _CODEX_CAPABILITY_GATE_TIMEOUT_SECONDS,
    _CODEX_CAPABILITY_PARK_CIRCUIT_THRESHOLD,
    _CODEX_CAPABILITY_PROBE_TTL_SECONDS,
    _SPAWN_ERROR_BACKOFF_CAP_SECONDS,
    _SPAWN_ERROR_BACKOFF_INITIAL_SECONDS,
    _cached_codex_capability_diagnosis,
    _claim_next_pending,
    _codex_capability_cache,
    _codex_capability_gate,
    _codex_capability_park_count,
    _emit_attempt_cap_blocked_event,
    _lane_occupants_for_client,
    _lane_stats_for_client,
    _park_running_task_blocked_on_user,
    _reset_codex_capability_cache,
    _revert_claimed_task_to_pending,
    _spawn_claimed_task,
    _SpawnOutcome,
)
from cw.dispatch.gating import (
    _AVAILABILITY_OUTAGE_REASON,
    _AVAILABILITY_PROBE_TIMEOUT_SECONDS,
    _AVAILABILITY_PROBE_TTL_SECONDS,
    FRESHNESS_MAIN_BEHIND,
    FRESHNESS_MAIN_DETACHED,
    FRESHNESS_MAIN_DIRTY_CHECKOUT,
    FRESHNESS_MAIN_DIVERGED,
    FRESHNESS_NON_MAIN_HEAD,
    _emit_availability_skip,
    _emit_stale_skip,
    _emit_usage_limit_skip_events,
    _invalidate_stale_context_json,
    _reconcile_usage_limited,
    _record_availability_block,
    _reset_availability_block,
    _resolve_availability,
    _resolve_availability_once,
    _resolve_freshness,
)
from cw.dispatch.lanes import (
    _LANE_PAUSE_SOURCE_CIRCUIT_BREAKER,
    _check_lane_circuit_paused,
    _ClientDispatchResult,
    _dispatch_client_lanes,
    _record_client_freshness_block,
    _record_lane_spawn_error,
    _reset_client_freshness_blocks,
    _reset_lane_spawn_errors,
    _resolve_dispatch_skip_reason,
    _resolve_low_precedence_skip_reason,
)
from cw.dispatch.loop import (
    _CW_PACKAGE_NAME,
    _DISPATCH_CONSUMER,
    _LOADED_VERSION,
    TICK_STALE_SECONDS,
    _apply_events_to_store,
    _resolve_loaded_version,
    consume_completed_sessions,
    persist_last_result,
    run_dispatch_loop,
)
from cw.dispatch.tick import (
    DispatchTickResult,
    _build_plan_order,
    _client_tick_snapshot,
    _ClientTickSnapshot,
    _sweep_expired_diagnostics,
    dispatch_tick,
)

__all__ = [
    "FRESHNESS_MAIN_BEHIND",
    "FRESHNESS_MAIN_DETACHED",
    "FRESHNESS_MAIN_DIRTY_CHECKOUT",
    "FRESHNESS_MAIN_DIVERGED",
    "FRESHNESS_NON_MAIN_HEAD",
    "TICK_STALE_SECONDS",
    "_APPROVAL_GATE_REASON",
    "_AVAILABILITY_OUTAGE_REASON",
    "_AVAILABILITY_PROBE_TIMEOUT_SECONDS",
    "_AVAILABILITY_PROBE_TTL_SECONDS",
    "_AWAITING_OPERATOR_REASON",
    "_CODEX_CAPABILITY_GATE_TIMEOUT_SECONDS",
    "_CODEX_CAPABILITY_PARK_CIRCUIT_THRESHOLD",
    "_CODEX_CAPABILITY_PROBE_TTL_SECONDS",
    "_CW_PACKAGE_NAME",
    "_DISPATCH_CONSUMER",
    "_INVALID_STAGE_REASON",
    "_LANE_PAUSE_SOURCE_CIRCUIT_BREAKER",
    "_LOADED_VERSION",
    "_PLAN_PARKED_REASON",
    "_SPAWN_ERROR_BACKOFF_CAP_SECONDS",
    "_SPAWN_ERROR_BACKOFF_INITIAL_SECONDS",
    "_STAGE_REACHED_TO_STAGE",
    "_UNKNOWN_CLIENT_REASON",
    "DispatchTickResult",
    "_ClientDispatchResult",
    "_ClientTickSnapshot",
    "_SpawnOutcome",
    "_StagePosition",
    "_accumulate_task_cost",
    "_apply_events_to_store",
    "_build_plan_order",
    "_cached_codex_capability_diagnosis",
    "_check_lane_circuit_paused",
    "_claim_next_pending",
    "_classify_sentinel_stage_position",
    "_client_tick_snapshot",
    "_codex_capability_cache",
    "_codex_capability_gate",
    "_codex_capability_park_count",
    "_dispatch_client_lanes",
    "_emit_attempt_cap_blocked_event",
    "_emit_availability_skip",
    "_emit_stale_skip",
    "_emit_usage_limit_skip_events",
    "_extract_scope_tier",
    "_invalidate_stale_context_json",
    "_lane_occupants_for_client",
    "_lane_stats_for_client",
    "_park_running_task_blocked_on_user",
    "_persist_carried_context",
    "_reconcile_usage_limited",
    "_record_availability_block",
    "_record_client_freshness_block",
    "_record_lane_spawn_error",
    "_reset_availability_block",
    "_reset_client_freshness_blocks",
    "_reset_codex_capability_cache",
    "_reset_lane_spawn_errors",
    "_resolve_availability",
    "_resolve_availability_once",
    "_resolve_dispatch_skip_reason",
    "_resolve_freshness",
    "_resolve_loaded_version",
    "_resolve_low_precedence_skip_reason",
    "_resolve_scope_tier",
    "_resolve_stage_walk",
    "_revert_claimed_task_to_pending",
    "_route_scope_gated_approval",
    "_route_stage_success",
    "_route_staged_decision",
    "_should_gate_for_signoff",
    "_spawn_claimed_task",
    "_stage_advance_unchecked",
    "_sweep_expired_diagnostics",
    "_walk_stage_pointer_forward",
    "apply_staged_decision",
    "consume_completed_sessions",
    "dispatch_tick",
    "persist_last_result",
    "resolve_signoff",
    "run_dispatch_loop",
]
